apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: swgnj3qvp-nodejs 
  janus-idp.io/tekton: swgnj3qvp-nodejs
  backstage.io/kubernetes-id: swgnj3qvp-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: swgnj3qvp-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml