apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: swgnj3qvp-nodejs-gitops
  description: This is GitOps manifest for swgnj3qvp-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=swgnj3qvp-nodejs
    backstage.io/kubernetes-id: swgnj3qvp-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: swgnj3qvp-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:swgnj3qvp-nodejs
