apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: swgnj3qvp-nodejs
  janus-idp.io/tekton: swgnj3qvp-nodejs
  backstage.io/kubernetes-id: swgnj3qvp-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: swgnj3qvp-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
