apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: swgnj3qvp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: swgnj3qvp-nodejs 
  name: swgnj3qvp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: swgnj3qvp-nodejs 
